cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'awsebcli'
brew 'coreutils'
brew 'docker'
brew 'go'
brew 'grc'
brew 'heroku'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'zsh-autosuggestions'

cask '1password'
cask 'firefox'
# cask 'google-chrome'
cask 'slack'
cask 'docker'
cask 'skitch'
# cask 'postico'
cask 'sketch'
cask 'google-drive-file-stream'
cask 'ngrok'
cask 'kap'
cask 'fastlane'
# cask 'genymotion'
# cask 'java'
# cask 'android-studio'
cask 'soulver'
cask 'charles'